version: '3.8'

services:
  # Docker para o banco de dados
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Docker à API Spring Boot
  api:
    image: api_todolist  # (opcional) nome da imagem resultante
    container_name: api_todolist
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8086:8086"
    depends_on:
      - db

volumes:
  mysql_data:
